print("Hello, World!")
print("This is a test file for Git.")
print("Let's learn how to use Git effectively.")
print("This file will be used to demonstrate Git commands and workflows.")
print("Adicionando linha no arquivo teste_git.py para testar o git add e git commit e git merge")
